on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install required packages for SlopOS development
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          nasm \
          make \
          xorriso \
          grub-pc-bin \
          grub-common \
          mtools \
          qemu-system-x86 \
          qemu-system-i386 \
          libc6-dev-i386 \
          build-essential
    
    - name: Verify package installation
      run: |
        echo "Verifying installed packages..."
        which gcc nasm make xorriso grub-mkrescue qemu-system-x86_64
        gcc --version
        nasm --version
        qemu-system-x86_64 --version | head -1
    
